replicas:
  _default: 1
  dev: 3

selector : dev

name:
  app: demo-helm

service:
  nameApp: demo-helm-service
  type: NodePort
  port: 80
  targetPort: 8000

image:
  repository: bobah165/arch
  tag: v5

ingress:
  enabled: false
  name: "demo-helm-ingress"
  className: nginx
  host: "arch.homework"
  pathType: Prefix
  path:
    person: /api/person
    health: /health

db:
  url: jdbc:postgresql://my-db-postgresql:5432/postgres


app:
  db:
    password:
      _default: MTIzNDU2
    username:
      _default: cG9zdGdyZXM=

