spring:
  application:
    name: demo-app
  datasource:
    url: jdbc:postgresql://my-db-postgresql:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

server:
  port: 8000
  shutdown: graceful
